version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      pagefind-and-vercel-cli:
        patterns:
          - "vercel"
          - "pagefind"
          - "@pagefind/default-ui"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
