import type { NextConfig } from "next";
import {
  BLOG_DRAFT_LEAK_GUARD_MSG_PREVIEW,
  BLOG_DRAFT_LEAK_GUARD_MSG_PRODUCTION,
  checkVercelDraftGuard as checkBlogDraftGuard,
} from "./src/lib/blog-errors";
import {
  PROJECTS_DRAFT_LEAK_GUARD_MSG_PREVIEW,
  PROJECTS_DRAFT_LEAK_GUARD_MSG_PRODUCTION,
  checkVercelDraftGuard as checkProjectsDraftGuard,
} from "./src/lib/project-errors";

const __isUnderVitest = process.env.VITEST === "true";

/*
 * Early-stderr env-var-scoping guard (Operator-error UX Layer 1).
 *
 * Runs at module top level before any Next.js prerender wrapper. If the
 * Vercel build env reflects a draft-leak misconfiguration, write the named
 * diagnostic to stderr and exit non-zero — this surfaces at a log layer
 * Vercel is less likely to re-format than the deeper getPublishedPosts()
 * rethrow path. Local dev (VERCEL unset) is unaffected.
 *
 * Source-of-truth for the error message bodies and the underlying check:
 *   src/lib/blog-errors.ts (blog)
 *   src/lib/project-errors.ts (projects)
 *
 * Fix (Vercel UI): Project Settings → Environment Variables → ensure
 *   BLOG_INCLUDE_DRAFTS / PROJECTS_INCLUDE_DRAFTS are set on Preview scope
 *   only (NOT Production).
 *
 * See Req 7.3 in .spec-workflow/specs/blog-core/requirements.md and
 * .spec-workflow/specs/project-showcase/requirements.md, plus the
 * design.md "Operator-error UX" + "next.config.ts (extension)" sections.
 *
 * Under Vitest (`process.env.VITEST === "true"`), runDraftGuard writes the
 * diagnostic but does NOT call `process.exit(1)` — the gate prevents the
 * test runner from being killed mid-suite while still surfacing the message.
 */
function runDraftGuard(
  guard: { kind: "production" | "preview" } | null,
  msgProd: string,
  msgPreview: string,
): void {
  if (!guard) return;
  const msg = guard.kind === "production" ? msgProd : msgPreview;
  console.error(msg);
  if (!__isUnderVitest) process.exit(1);
}

runDraftGuard(
  checkBlogDraftGuard(),
  BLOG_DRAFT_LEAK_GUARD_MSG_PRODUCTION,
  BLOG_DRAFT_LEAK_GUARD_MSG_PREVIEW,
);
runDraftGuard(
  checkProjectsDraftGuard(),
  PROJECTS_DRAFT_LEAK_GUARD_MSG_PRODUCTION,
  PROJECTS_DRAFT_LEAK_GUARD_MSG_PREVIEW,
);

const cspDirectives = [
  "default-src 'self'",
  // `'wasm-unsafe-eval'` is required by Pagefind's WebAssembly index runtime
  // loaded by <SiteSearch /> via dynamic import of /pagefind/pagefind.js.
  // Without it, the search dialog's WASM instantiation throws a CSP error
  // and Pagefind cannot return results. Scoped to script-src only — does
  // not allow eval() in JavaScript.
  "script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "frame-src 'self'",
  "connect-src 'self'",
  "form-action 'self'",
].join("; ");

const nextConfig: NextConfig = {
  headers: async () => {
    const routes = [
      {
        source: "/((?!playground(?:/|$)).*)",
        headers: [
          {
            key: "Content-Security-Policy",
            value: cspDirectives,
          },
        ],
      },
    ];
    if (process.env.VERCEL_ENV === "preview") {
      routes.push({
        source: "/(.*)",
        headers: [
          {
            key: "X-Robots-Tag",
            value: "noindex, nofollow",
          },
        ],
      });
    }

    /*
     * Hidden-post defensive `X-Robots-Tag` (Req 7.4, 7.11).
     *
     * Policy: applies to posts with `hiddenFromLists === true` ONLY,
     * regardless of `excludeFromSearch` (per blog-enhanced design v4 §1
     * fourth bullet). `excludeFromSearch` governs Pagefind indexing only;
     * search-engine visibility is gated by `hiddenFromLists`.
     *
     * Defense-in-depth alongside the per-page `<meta name="robots">` tag —
     * bots parsing headers but not HTML still see noindex.
     *
     * The Velite output (`./.velite/index.js`) is generated by `pnpm build`
     * and may be absent on a fresh checkout. Wrap the import in try/catch
     * with an empty-array fallback so `next build` succeeds even before
     * Velite has run.
     */
    let hiddenRoutes: string[] = [];
    try {
      const { posts } = (await import("./.velite/index.js")) as {
        posts: Array<{ slug: string; draft?: boolean; hiddenFromLists?: boolean }>;
      };
      hiddenRoutes = posts
        .filter((p) => p.hiddenFromLists === true && !p.draft)
        .map((p) => `/blog/${p.slug}`);
    } catch {
      hiddenRoutes = [];
    }
    for (const route of hiddenRoutes) {
      routes.push({
        source: route,
        headers: [
          {
            key: "X-Robots-Tag",
            value: "noindex, nofollow",
          },
        ],
      });
    }

    return routes;
  },

  /*
   * 301 redirects from the legacy WordPress.com site (matthew-field.ca).
   * Dated post permalinks map to their new /blog/<slug> routes; posts that
   * were not migrated and the old standalone pages map to the nearest
   * equivalent. Next.js normalizes trailing slashes before matching, so the
   * sources are written without one.
   */
  redirects: async () => [
    // Migrated posts — old dated permalink → new /blog/<slug>.
    {
      source:
        "/2024/07/16/importing-certificates-in-nvidia-gpu-operator-for-private-apt-repository-ubuntu-20-04",
      destination:
        "/blog/importing-certificates-in-nvidia-gpu-operator-for-private-apt-repository-ubuntu-20-04",
      permanent: true,
    },
    {
      source: "/2024/08/09/installing-obsidian-on-wsl-with-a-windows-gui-easy-setup",
      destination: "/blog/installing-obsidian-on-wsl-with-a-windows-gui-easy-setup",
      permanent: true,
    },
    {
      source: "/2020/04/04/azure-vm-provisioning-timeout-failure-black-screen-boot-diagnostics",
      destination: "/blog/azure-vm-provisioning-timeout-failure-black-screen-boot-diagnostics",
      permanent: true,
    },
    {
      source: "/2020/02/25/the-financial-crisis-of-2008",
      destination: "/blog/the-financial-crisis-of-2008",
      permanent: true,
    },
    {
      source: "/2020/02/25/making-ethical-decisions-in-a-post-modern-technological-landscape",
      destination: "/blog/making-ethical-decisions-in-a-post-modern-technological-landscape",
      permanent: true,
    },
    // Posts not migrated → blog index.
    { source: "/2022/09/07/making-a-i-art", destination: "/blog", permanent: true },
    { source: "/2020/10/24/cave-drips", destination: "/blog", permanent: true },
    {
      source: "/2020/03/27/quicktip-visios-fit-to-drawing-function",
      destination: "/blog",
      permanent: true,
    },
    // Legacy standalone pages → nearest equivalent on the new site.
    { source: "/technical-portfolio", destination: "/projects", permanent: true },
    { source: "/handy-tools", destination: "/resources", permanent: true },
    { source: "/blog-feed", destination: "/blog", permanent: true },
  ],
};

export default nextConfig;
